In [1]:
#5_QueryDataUsingOpenSafelyCodelist.ipynb



library(bigrquery)
library(lubridate) # required for datetime



project_id = "yhcr-prd-phm-bia-core"

targetdb <-'yhcr-prd-phm-bia-core.CB_MYSPACE_JDB'
sourcedb <-'yhcr-prd-phm-bia-core.CB_FDM_PrimaryCare_V8'

Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [3]:
sql63 <-paste('SELECT distinct per.person_id 
, date_diff(current_date,birth_datetime,YEAR) as age
, sr.dateeventrecorded
 FROM ', targetdb , '.tuberculosis tub
 , ' ,sourcedb,'.tbl_srcode sr
 , ' ,sourcedb,'.person per
 where tub.code = sr.ctv3code
 and sr.person_id = per.person_id 
 and sr.dateeventrecorded >"1969-12-31 23:59:59" ', sep = "")

tb63 <-bq_project_query(project_id, sql63)


table <- bq_table_download(tb63)
# This line below just displays the data.
table

      person_id age dateeventrecorded
1     12631597   71 2019-01-23 09:03:23
2     14984264   16 2022-11-07 15:45:41
3     13523692  101 2006-07-14 00:00:00
4     13012424  102 2007-10-10 11:15:38
5     12695932   61 2015-01-09 09:30:45
6     13171378   52 2010-06-08 09:53:28
7     13310830    9 2014-11-11 16:12:42
8     13472671   52 2002-09-11 12:11:49
9     13286991   70 2005-11-14 00:00:00
10    13703898   60 2009-01-14 12:44:50
11     1634632   42 2008-08-05 14:36:15
12    11433434   30 2023-04-13 16:05:40
13    12487531   74 2006-07-21 00:00:00
14    13291082   45 2003-05-13 10:17:52
15    13464104   93 2006-01-18 15:31:13
16    12988869   73 2006-11-02 10:28:49
17    12936629   59 2008-11-19 10:48:02
18    13480211   50 2008-02-25 12:01:06
19    13354625   96 2008-08-18 14:15:14
20    13431449   63 2009-05-18 00:00:00
21      887655   74 2008-09-22 00:00:00
22    12753684   45 2008-01-22 11:15:30
23    13622369   27 2022-09-26 11:11:10
24      678870   19 2007-11-06 11:10:47
25    12430038   37 2011-10-14 13:33:37
26    13578957   89 2009-03-24 09:41:36
27    12521555   48 2018-10-17 13:05:29
28      994241   84 2011-02-04 15:59:32
29      972635   36 2012-02-28 14:38:52
30    12590258   64 2006-01-30 10:42:10
⋮     ⋮         ⋮   ⋮
16203 13095786   27 2013-08-28 11:27:50
16204 13374692   46 2007-04-23 09:35:42
16205 13132525   37 2013-02-15 10:29:28
16206 12878710   84 2018-11-29 09:39:24
16207   795206   95 2002-11-07 00:00:00
16208 12796560   18 2010-02-05 14:35:24
16209 12391467   52 2023-05-19 11:28:29
16210 13382677   56 2014-03-19 11:43:51
16211 12595413   40 2016-11-07 11:27:53
16212 13013155   81 2003-04-10 10:24:10
16213 12941568   18 2006-07-20 11:47:10
16214   720255   39 2006-07-26 10:32:08
16215 12949577   42 2008-03-25 11:40:54
16216 13642966   78 2007-10-03 00:00:00
16217 13387932   69 2005-12-10 00:00:00
16218 12639835   20 2010-01-16 00:00:00
16219 12689486   66 2006-08-18 11:22:55
16220 12676425   89 2008-07-07 14:37:22
16221  1026220   33 2012-03-07 13:56:27
16222 10647422   33 2022-08-05 08:51:55
16223 13499625   54 2011-02-18 11:07:33
16224   720943   31 2012-02-24 10:46:25
16225 12554442   84 2009-05-27 12:35:36
16226 12570168   59 2020-08-19 11:17:28
16227 13714218   66 2010-10-25 00:00:00
16228 12797809   65 2001-05-08 12:36:59
16229 13090182   35 2012-08-15 12:22:42
16230 13688144  109 2009-01-26 00:00:00
16231 12822640   86 2010-01-16 00:00:00
16232    94512   28 2005-07-25 09:43:13